name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Where to deploy
        options:
        - stage
        - prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout
        uses: actions/checkout@v4
      - name: Authenticate with GCP
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}
      - name: Setup gcloud SDK
        id: setup-gcloud
        uses: google-github-actions/setup-gcloud@v2
      - name: GCP Authentication for Docker
        id: docker-auth
        uses: docker/login-action@v1
        with:
          username: _json_key
          password: ${{ secrets.GCP_CREDENTIALS_JSON }}
          registry: asia-south1-docker.pkg.dev
      - name: Build and push the container
        id: docker-build-push
        env:
          build_tag: asia-south1-docker.pkg.dev/marketfeed-stage/test-cloud-run-deployment/cloud-run-deployments:${{ github.sha }}
        run: |-
          docker build -t $build_tag .
          docker push $build_tag
      - name: Read env vars
        id: read-env-vars
        run: |
          echo '::set-output name=ENV_VARS::${{secrets.ENV_VARS}}'
      - name: Deploy container to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: cloud-run-deployments
          region: asia-south1
          image: asia-south1-docker.pkg.dev/marketfeed-stage/test-cloud-run-deployment/cloud-run-deployments:${{ github.sha }}
          env_vars: ${{steps.read-env-vars.outputs.ENV_VARS}}
      - name: Output service URL
        run: echo ${{ steps.deploy.outputs.url }}

