name: deploy

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: show secret
        id: show
        run: |
          echo "${{ secrets.ENV_VARS }}" > .env.yaml
          echo "ENV_YAML<<EOF" >> $GITHUB_ENV
          echo "${{ secrets.ENV_VARS }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: release
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: .env.yaml
