name: deploy

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: show secret
        run: |-
          echo ${{ secrets.ENV_VARS }} > .env.yaml
          cat .env.yaml | sed 's/./& /g'
