name: deploy

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: show secret
        id: show
        run: |
          echo ${{ secrets.ENV_VARS }} >> $GITHUB_ENV
